# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "PROGRAMMER'S BY-PRODUCTS"
description: > # this means to ignore newlines until "email:"
   Mostly on programming.

email: lukasz@lelinski.pl
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/blog-cover.jpg"

name: 'Lukasz Lelinski'
author: 'Lukasz Lelinski'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://programmersbyproducts.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@lukaleli'


#fill in disqus shortname to use disqus
disqus: twitter-584190719

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/lukaleli
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/programmersbyproducts/
    desc: Connect with me on facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/lukaleli
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
